// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCai6_9fH4hGmFunSLFDM7lAa1931BW-_I',
    appId: '1:174456400808:web:4079e28917b36e985c4b9d',
    messagingSenderId: '174456400808',
    projectId: 'nishantstore-e5cbf',
    authDomain: 'nishantstore-e5cbf.firebaseapp.com',
    storageBucket: 'nishantstore-e5cbf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrLOWFaMd3ZHgUN5uHN7-ii72B6kTDBec',
    appId: '1:174456400808:android:18778b4c84b0a15a5c4b9d',
    messagingSenderId: '174456400808',
    projectId: 'nishantstore-e5cbf',
    storageBucket: 'nishantstore-e5cbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDulfTkfNQQM3vXGdEJuu9FJgmK6PhzE_U',
    appId: '1:174456400808:ios:8fccb48e0d41be385c4b9d',
    messagingSenderId: '174456400808',
    projectId: 'nishantstore-e5cbf',
    storageBucket: 'nishantstore-e5cbf.firebasestorage.app',
    androidClientId: '174456400808-c7a4n7m9udkcj96g666pgquk1egli0hb.apps.googleusercontent.com',
    iosClientId: '174456400808-ndbu2561nfm4ug3o7v515ak43g5vs0di.apps.googleusercontent.com',
    iosBundleId: 'com.example.nishantStore',
  );

}